//! The Oh-My-Pi adapter, ported from `SirioAgents/OhMyPiAdapter.swift`.

use std::path::Path;

use crate::error::PrepareError;
use crate::shell_quote::{json_string_literal, shell_quote};

/// The hook template, byte-faithful to the Swift original. `__SIRIOCTL__`
/// and `__PANE__` are replaced by [`prepare`]; the JS braces are left
/// untouched (no `format!` interpolation).
const HOOK_TEMPLATE: &str = "// Generated by Sirio — drives the sidebar badge for this pane and
// reports the omp session identity for restore.
export default function (pi) {
    const notify = (status, extra = []) => {
        void pi.exec(__SIRIOCTL__, [\"notify\", \"--session\", \"__PANE__\", \"--status\", status, ...extra]);
    };
    pi.on(\"session_start\", async (payload) => {
        const id = payload?.session?.id ?? payload?.sessionId ?? payload?.session?.file ?? \"\";
        notify(\"running\", id ? [\"--agent-session\", String(id)] : []);
    });
    pi.on(\"turn_start\", async () => { notify(\"running\"); });
    pi.on(\"turn_end\", async () => { notify(\"needs-input\"); });
    pi.on(\"session_shutdown\", async () => { notify(\"done\"); });
}
";

/// Oh-My-Pi (omp) supports native TypeScript hook files loaded via
/// `--hook <file>`. `prepare` writes the hook file inside the worktree —
/// never global config; the hook calls `sirioctl notify` on lifecycle
/// events to drive the badge.
pub struct OhMyPiAdapter;

impl super::AgentAdapter for OhMyPiAdapter {
    fn id(&self) -> &'static str {
        "omp"
    }

    fn display_name(&self) -> &'static str {
        "Oh-My-Pi"
    }

    fn executable_name(&self) -> &'static str {
        // The binary is `omp`, exactly as the Swift original spells it.
        //
        // This spent three passes as `oh-my-pi` because npm carries two
        // unrelated packages whose names collide. `oh-my-pi` (acidsugarx,
        // 0.2.0, `main: ./dist/extension.js`) is a broken VS Code
        // extension that installs an `oh-my-pi` binary which cannot
        // start. The agent is `@oh-my-pi/pi-coding-agent`
        // (github.com/can1357/oh-my-pi, omp.sh), whose `bin` is `omp`.
        // A pass verified the old name by checking that *something*
        // called `oh-my-pi` was on PATH; something was, and it was the
        // wrong program. Presence of a name is not identity — check
        // `--version`.
        //
        // Live, 2026-08-19, omp v17.3.8: `omp --hook <file> --print
        // --no-tools <prompt>` loaded this adapter's generated hook and
        // fired session_start, turn_start, turn_end and session_shutdown
        // in order, each reaching `sirioctl notify`.
        "omp"
    }

    fn has_native_hooks(&self) -> bool {
        true
    }

    fn skill_markdown(&self) -> Option<&'static str> {
        // F-AGENT-SAFE-01: see `ClaudeCodeAdapter::skill_markdown`.
        Some(include_str!("../../../../skills/sirio/SKILL.md"))
    }

    fn prepare(
        &self,
        worktree_path: &str,
        pane_id: &str,
        sirioctl_path: &str,
    ) -> Result<(), PrepareError> {
        if let Some(markdown) = self.skill_markdown() {
            crate::install_skill(markdown, self.id(), worktree_path)?;
        }
        let dir = Path::new(worktree_path).join(".sirio");
        std::fs::create_dir_all(&dir)?;

        let hook = HOOK_TEMPLATE
            .replace("__SIRIOCTL__", &json_string_literal(sirioctl_path))
            .replace("__PANE__", pane_id);

        std::fs::write(dir.join("omp-hook.ts"), hook)?;
        Ok(())
    }

    fn command(&self, worktree_path: &str, _pane_id: &str, _sirioctl_path: &str) -> String {
        let hook_path = format!("{worktree_path}/.sirio/omp-hook.ts");
        format!("omp --hook {}", shell_quote(&hook_path))
    }

    fn resume_command(
        &self,
        worktree_path: &str,
        _pane_id: &str,
        _sirioctl_path: &str,
        session_ref: &str,
    ) -> Option<String> {
        let hook_path = format!("{worktree_path}/.sirio/omp-hook.ts");
        Some(format!(
            "omp --hook {} --resume={}",
            shell_quote(&hook_path),
            shell_quote(session_ref)
        ))
    }

    fn builtin_acp(&self) -> Option<crate::AcpProgram> {
        // Flipped on 2026-09-13, on the terms the previous comment set: this
        // stayed `None` only because no omp had been installed anywhere the
        // claim could be checked, and `tests/acp_conformance.rs` was skipping
        // rather than proving it. omp 18.1.19 answers the ACP `initialize`
        // handshake on stdin with `{"protocolVersion":1,"agentInfo":{"name":
        // "oh-my-pi",...}}`, so that test now runs for real and holds the
        // claim to it — the claim is not trusted, it is checked on every
        // machine that has the binary. The retired Swift app launched the
        // same subcommand (AgentLaunchSpec.swift:73-75 at 5430d7bf).
        Some(crate::AcpProgram::new("omp", &["acp"]))
    }

    fn summarizer_command(&self, prompt: &str) -> Option<String> {
        // F-AGENT-OMP-03. Live, 2026-08-19: `omp --print --no-tools
        // 'Reply with exactly the word: ALIVE'` printed `ALIVE` on
        // stdout, which is the summarizer contract.
        Some(format!("omp --print --no-tools {}", shell_quote(prompt)))
    }
}
