//! The OpenCode adapter, ported from `SirioAgents/OpenCodeAdapter.swift`.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::GlobalHookInstall;
use crate::error::PrepareError;
use crate::shell_quote::{json_string_literal, shell_quote};

/// The plugin template, byte-faithful to the Swift original. `__SIRIOCTL__`
/// and `__PANE__` are replaced by [`prepare`]; the braces in the JS template
/// literal are left untouched (no `format!` interpolation).
const PLUGIN_TEMPLATE: &str = "// Generated by Sirio — reports the OpenCode session id for restore.
export const SirioSession = async ({ $ }) => {
  let reported = \"\"
  const sirioctl = __SIRIOCTL__
  const pane = \"__PANE__\"
  return {
    event: async ({ event }) => {
      const id = event?.properties?.info?.id
      if (event?.type === \"session.updated\" && id && id !== reported) {
        reported = id
        await $`${sirioctl} session-ref --session ${pane} --ref ${id}`.quiet().nothrow()
      }
    },
  }
}
";

/// The user-global variant of [`PLUGIN_TEMPLATE`]: one file serves every
/// pane, so it names none — sirioctl resolves the pane from the
/// `SIRIO_PANE_ID` opencode inherited, and stays silent outside a Sirio
/// pane. Only `__SIRIOCTL__` is replaced.
const GLOBAL_PLUGIN_TEMPLATE: &str =
    "// Generated by Sirio — reports the OpenCode session id for restore.
// Installed user-globally from Sirio's Settings; the pane comes from the
// SIRIO_PANE_ID a Sirio terminal exports, so outside one this is inert.
export const SirioSession = async ({ $ }) => {
  let reported = \"\"
  const sirioctl = __SIRIOCTL__
  return {
    event: async ({ event }) => {
      const id = event?.properties?.info?.id
      if (event?.type === \"session.updated\" && id && id !== reported) {
        reported = id
        await $`${sirioctl} session-ref --ref ${id}`.quiet().nothrow()
      }
    },
  }
}
";

/// OpenCode has no lifecycle hook mechanism for status — Sirio watches the
/// pane's exit code. `prepare` writes a worktree-local plugin (never global
/// config) whose only job is reporting the session id via
/// `sirioctl session-ref`, keeping the status pipeline untouched.
pub struct OpenCodeAdapter;

impl super::AgentAdapter for OpenCodeAdapter {
    fn id(&self) -> &'static str {
        "opencode"
    }

    fn display_name(&self) -> &'static str {
        "OpenCode"
    }

    fn has_native_hooks(&self) -> bool {
        false
    }

    fn skill_markdown(&self) -> Option<&'static str> {
        // F-AGENT-SAFE-01: see `ClaudeCodeAdapter::skill_markdown`.
        Some(include_str!("../../../../skills/sirio/SKILL.md"))
    }

    fn prepare(
        &self,
        worktree_path: &str,
        pane_id: &str,
        sirioctl_path: &str,
    ) -> Result<(), PrepareError> {
        if let Some(markdown) = self.skill_markdown() {
            crate::install_skill(markdown, self.id(), worktree_path)?;
        }
        let dir = Path::new(worktree_path).join(".opencode/plugin");
        std::fs::create_dir_all(&dir)?;

        let plugin = PLUGIN_TEMPLATE
            .replace("__SIRIOCTL__", &json_string_literal(sirioctl_path))
            .replace("__PANE__", pane_id);

        std::fs::write(dir.join("sirio-session.js"), plugin)?;
        Ok(())
    }

    fn install_global_hooks(
        &self,
        home: &Path,
        environment: &BTreeMap<String, String>,
        sirioctl_path: &str,
    ) -> Result<GlobalHookInstall, PrepareError> {
        // OpenCode's config directory: `$OPENCODE_CONFIG_DIR`, else
        // `$XDG_CONFIG_HOME/opencode`, else `~/.config/opencode` — the
        // lookup `opencode` itself performs (`Global.Path.config`), on
        // Windows included. Its documented user-global plugin directory is
        // `plugins/` (the binary also scans the older singular `plugin/`
        // the worktree-local adapter still writes).
        let config_dir = environment
            .get("OPENCODE_CONFIG_DIR")
            .filter(|value| !value.is_empty())
            .map(PathBuf::from)
            .or_else(|| {
                environment
                    .get("XDG_CONFIG_HOME")
                    .filter(|value| !value.is_empty())
                    .map(|xdg| Path::new(xdg).join("opencode"))
            })
            .unwrap_or_else(|| home.join(".config").join("opencode"));
        let dir = config_dir.join("plugins");
        std::fs::create_dir_all(&dir)?;

        let plugin =
            GLOBAL_PLUGIN_TEMPLATE.replace("__SIRIOCTL__", &json_string_literal(sirioctl_path));
        let path = dir.join("sirio-session.js");
        std::fs::write(&path, plugin)?;
        Ok(GlobalHookInstall::Written(path))
    }

    fn command(&self, _worktree_path: &str, _pane_id: &str, _sirioctl_path: &str) -> String {
        "opencode".to_string()
    }

    fn resume_command(
        &self,
        _worktree_path: &str,
        _pane_id: &str,
        _sirioctl_path: &str,
        session_ref: &str,
    ) -> Option<String> {
        Some(format!("opencode --session {}", shell_quote(session_ref)))
    }

    fn builtin_acp(&self) -> Option<crate::AcpProgram> {
        // Verified live on 2026-08-23 against opencode 1.18.21: piping an
        // ACP `initialize` into `opencode acp` returns
        // `agentInfo: {"name":"OpenCode","version":"1.18.21"}` with
        // sessionCapabilities close/fork/list/resume. The registry agrees —
        // its own `opencode` entry carries `cmd: "./opencode",
        // args: ["acp"]`.
        Some(crate::AcpProgram::new("opencode", &["acp"]))
    }

    fn summarizer_command(&self, prompt: &str) -> Option<String> {
        // `--pure` suppresses the TUI chrome so stdout is only the answer.
        Some(format!("opencode run --pure {}", shell_quote(prompt)))
    }
}
