query MergeRequestHeader($fullPath: ID!, $iid: String!) {
  project(fullPath: $fullPath) {
    mergeRequest(iid: $iid) {
      ...MergeRequestSummary
      id
      discussionLocked
      userPermissions { createNote updateMergeRequest }
      labels { nodes { id title color } }
      description
      diffRefs { baseSha headSha startSha }
      notes(last: 100) {
        pageInfo { hasPreviousPage }
        nodes { id userPermissions { adminNote } author { username } body createdAt system position { filePath newLine oldLine } }
      }
    }
  }
}
