// Generated by Tiller — drives the sidebar badge for this pane and
// reports the omp session identity for restore.
export default function (pi) {
    const notify = (status, extra = []) => {
        void pi.exec("/Users/enzopiopalmisano/Library/Application Support/Tiller/bin/tillerctl", ["notify", "--session", "B6B97CBB-4C30-493A-9721-0C9D40E2AB1F", "--status", status, ...extra]);
    };
    pi.on("session_start", async (payload) => {
        const id = payload?.session?.id ?? payload?.sessionId ?? payload?.session?.file ?? "";
        notify("running", id ? ["--agent-session", String(id)] : []);
    });
    pi.on("turn_start", async () => { notify("running"); });
    pi.on("turn_end", async () => { notify("needs-input"); });
    pi.on("session_shutdown", async () => { notify("done"); });
}