#!/usr/bin/env python3
"""Freeze Sirio's theme presets from the baseline token dump.

Reads docs/testing/theme-ely-palette/before/{sirio,ely}.tsv (written by
`cargo run -p sirio_ui --example theme_dump` on the baseline commit) and
docs/testing/theme-ely-palette/rename.tsv, and writes
rust/crates/sirio_theme/src/presets.rs.

A field whose value is the same for all seven base colours, in both
appearances, goes into the per-appearance `Semantic` block; every other
field into the per-base-and-appearance `Ladder` block (spec §3.4).

Refuses to write if a token renamed to an Ely field differs from that
field's value in any combination: the renaming rule of spec §3.1.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
BEFORE = ROOT / "docs/testing/theme-ely-palette/before"
RENAME = ROOT / "docs/testing/theme-ely-palette/rename.tsv"
OUT = ROOT / "rust/crates/sirio_theme/src/presets.rs"

BASES = ["Neutral", "Stone", "Zinc", "Gray", "Slate", "Notte", "Onice"]
APPEARANCES = ["Dark", "Light"]


def read(path):
    rows = {}
    for line in path.read_text().splitlines():
        combo, token, *hsla = line.split("\t")
        rows[(combo, token)] = tuple(hsla)
    return rows


def literal(value):
    return "c(" + ", ".join("f32::NAN" if x == "NaN" else x for x in value) + ")"


def ident(field):
    return field.replace(".", "_")


def main():
    sirio = read(BEFORE / "sirio.tsv")
    ely = read(BEFORE / "ely.tsv")
    rename = dict(
        line.split("\t")
        for line in RENAME.read_text().splitlines()
        if line and not line.startswith("#")
    )
    ely_names = [t for (c, t) in ely if c == "Neutral/Dark/opaque"]
    sirio_names = []
    for new in rename.values():
        if new.startswith("sirio.") and new not in sirio_names:
            sirio_names.append(new)
    if len(sirio_names) != 21:
        sys.exit(f"expected 21 sirio.* targets, found {len(sirio_names)}")

    values = {}  # field -> {(base, appearance): value}
    for base in BASES:
        for app in APPEARANCES:
            for fade in ("opaque", "translucent"):
                combo = f"{base}/{app}/{fade}"
                for old, new in rename.items():
                    if new.startswith("ely.") and sirio[(combo, old)] != ely[(combo, new[4:])]:
                        sys.exit(f"{combo}: {old} {sirio[(combo, old)]} is not Ely's {new} {ely[(combo, new[4:])]}")
            combo = f"{base}/{app}/opaque"
            for name in ely_names:
                values.setdefault("ely." + name, {})[(base, app)] = ely[(combo, name)]
            for old, new in rename.items():
                if new.startswith("sirio."):
                    seen = values.setdefault(new, {}).get((base, app))
                    if seen is not None and seen != sirio[(combo, old)]:
                        sys.exit(f"{combo}: aliases of {new} disagree")
                    values[new][(base, app)] = sirio[(combo, old)]

    fields = ["ely." + n for n in ely_names] + sirio_names
    semantic = [
        f for f in fields
        if all(len({values[f][(b, a)] for b in BASES}) == 1 for a in APPEARANCES)
    ]
    ladder = [f for f in fields if f not in semantic]

    def block(name, members, pick):
        lines = [f"const {name}: {'Semantic' if members is semantic else 'Ladder'} = {'Semantic' if members is semantic else 'Ladder'} {{"]
        lines += [f"    {ident(f)}: {literal(pick(f))}," for f in members]
        return lines + ["};", ""]

    def expr(f):
        return f"{'s' if f in semantic else 'l'}.{ident(f)}"

    out = [
        "// @generated by Scripts/theme/freeze-presets.py from",
        "// docs/testing/theme-ely-palette/before — do not edit by hand. Change the",
        "// generator's input and regenerate. Provenance: docs/THEME-PROVENANCE.md.",
        "",
        "use ely_palette::{Palette, Syntax};",
        "use gpui::Hsla;",
        "",
        "use crate::{Appearance, BaseColor, SirioColors};",
        "",
        "const fn c(h: f32, s: f32, l: f32, a: f32) -> Hsla {",
        "    Hsla { h, s, l, a }",
        "}",
        "",
        "/// Fields equal across all seven base colours, per appearance.",
        "struct Semantic {",
        *[f"    {ident(f)}: Hsla," for f in semantic],
        "}",
        "",
        "/// Fields that move with the base colour.",
        "struct Ladder {",
        *[f"    {ident(f)}: Hsla," for f in ladder],
        "}",
        "",
    ]
    for app in APPEARANCES:
        out += block(f"SEMANTIC_{app.upper()}", semantic, lambda f: values[f][(BASES[0], app)])
    for base in BASES:
        for app in APPEARANCES:
            out += block(f"LADDER_{base.upper()}_{app.upper()}", ladder, lambda f: values[f][(base, app)])

    colors = [n for n in ely_names if "." not in n]
    syntax = [n.split(".", 1)[1] for n in ely_names if n.startswith("syntax.")]
    out += [
        "/// The palette Ely holds and Sirio's own tokens, for one base colour and appearance.",
        "pub(crate) fn preset(base: BaseColor, appearance: Appearance) -> (Palette, SirioColors) {",
        "    let s = match appearance {",
        "        Appearance::Dark => &SEMANTIC_DARK,",
        "        Appearance::Light => &SEMANTIC_LIGHT,",
        "    };",
        "    let l = match (base, appearance) {",
        *[f"        (BaseColor::{b}, Appearance::{a}) => &LADDER_{b.upper()}_{a.upper()},"
          for b in BASES for a in APPEARANCES],
        "    };",
        "    let palette = Palette {",
        *[f"        {n}: {expr('ely.' + n)}," for n in colors],
        "        chart: [" + ", ".join(expr(f"ely.chart.{i}") for i in range(8)) + "],",
        "        ansi: [" + ", ".join(expr(f"ely.ansi.{i}") for i in range(16)) + "],",
        "        syntax: Syntax {",
        *[f"            {n}: {expr('ely.syntax.' + n)}," for n in syntax],
        "        },",
        "    };",
        "    let sirio = SirioColors {",
        *[f"        {f[6:]}: {expr(f)}," for f in sirio_names],
        "    };",
        "    (palette, sirio)",
        "}",
        "",
    ]
    OUT.write_text("\n".join(out))
    print(f"PRESETS WRITTEN: {len(semantic)} semantic, {len(ladder)} ladder fields -> {OUT}")


if __name__ == "__main__":
    main()
