import Foundation

/// Oh-My-Pi (omp) supports native TypeScript hook files loaded via
/// `--hook <file>` (see docs/contracts/agent-hook-capabilities.md).
/// prepare writes the hook file inside the worktree — never global config;
/// the hook calls `tillerctl notify` on lifecycle events to drive the badge.
public struct OhMyPiAdapter: AgentAdapter {
    public let id = "omp"
    public let displayName = "Oh-My-Pi"
    public var hasNativeHooks: Bool { true }

    public init() {}

    public func prepare(worktreePath: String, paneId: UUID, tillerctlPath: String) throws {
        let dir = URL(fileURLWithPath: worktreePath).appendingPathComponent(".tiller")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let hook = """
        // Generated by Tiller — drives the sidebar badge for this pane and
        // reports the omp session identity for restore.
        export default function (pi) {
            const notify = (status, extra = []) => {
                void pi.exec(\(jsonStringLiteral(tillerctlPath)), ["notify", "--session", "\(paneId.uuidString)", "--status", status, ...extra]);
            };
            pi.on("session_start", async (payload) => {
                const id = payload?.session?.id ?? payload?.sessionId ?? payload?.session?.file ?? "";
                notify("running", id ? ["--agent-session", String(id)] : []);
            });
            pi.on("turn_start", async () => { notify("running"); });
            pi.on("turn_end", async () => { notify("needs-input"); });
            pi.on("session_shutdown", async () => { notify("done"); });
        }
        """
        try hook.write(to: dir.appendingPathComponent("omp-hook.ts"), atomically: true, encoding: .utf8)
    }

    public func command(worktreePath: String, paneId: UUID, tillerctlPath: String) -> String {
        "omp --hook \(shellQuote("\(worktreePath)/.tiller/omp-hook.ts"))"
    }

    public func resumeCommand(worktreePath: String, paneId: UUID,
                              tillerctlPath: String, sessionRef: String) -> String? {
        "omp --hook \(shellQuote("\(worktreePath)/.tiller/omp-hook.ts")) --resume=\(shellQuote(sessionRef))"
    }
}
