import Foundation

/// OpenCode has no lifecycle hook mechanism for status (see
/// docs/contracts/agent-hook-capabilities.md) — Tiller watches the pane's
/// exit code. `prepare` writes a worktree-local plugin (never global
/// config) whose only job is reporting the session id via
/// `tillerctl session-ref`, keeping the status pipeline untouched.
public struct OpenCodeAdapter: AgentAdapter {
    public let id = "opencode"
    public let displayName = "OpenCode"
    public var hasNativeHooks: Bool { false }

    public init() {}

    public func prepare(
        worktreePath: String,
        paneId: UUID,
        tillerctlPath: String
    ) throws {
        let dir = URL(fileURLWithPath: worktreePath)
            .appendingPathComponent(".opencode/plugin")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let plugin = """
        // Generated by Tiller — reports the OpenCode session id for restore.
        export const TillerSession = async ({ $ }) => {
          let reported = ""
          const tillerctl = \(jsonStringLiteral(tillerctlPath))
          const pane = "\(paneId.uuidString)"
          return {
            event: async ({ event }) => {
              const id = event?.properties?.info?.id
              if (event?.type === "session.updated" && id && id !== reported) {
                reported = id
                await $`${tillerctl} session-ref --session ${pane} --ref ${id}`.quiet().nothrow()
              }
            },
          }
        }
        """
        try plugin.write(to: dir.appendingPathComponent("tiller-session.js"),
                         atomically: true, encoding: .utf8)
    }

    public func command(worktreePath: String, paneId: UUID, tillerctlPath: String) -> String {
        "opencode"
    }

    public func resumeCommand(worktreePath: String, paneId: UUID,
                              tillerctlPath: String, sessionRef: String) -> String? {
        "opencode --session \(shellQuote(sessionRef))"
    }
}
