#!/bin/bash
# Generates the Inno Setup script (.iss) for the per-user Windows installer
# (#310) from the one packaging identity source (#304) and the release version.
#
# Compiles nothing: ISCC.exe is Windows-only, so this machine never runs it
# (the release workflow compiles where ISCC lives). The generated file is not
# committed -- spec §8.4: templates live in the repo, filled artifacts do not.
# Write the output next to the binaries: ISCC resolves relative Source: paths
# against the .iss's own directory, and OutputBaseFilename then names the
# finished SirioSetup-<version>.exe.
#
# `OutputDir=.` is what actually puts it beside them, and it is load-bearing.
# OutputBaseFilename sets only the *name*; the directory is OutputDir, whose
# Inno default is an `Output` subdirectory of the script's own. Without the
# line, ISCC reports a successful compile and writes
# build/windows/Output/SirioSetup-<version>.exe while the release workflow
# looks for build/windows/SirioSetup-<version>.exe -- a green packaging step
# followed by "No files were found with the provided path", which is how the
# first run that ever reached the windows job failed, after building and
# packaging everything correctly.
set -euo pipefail

usage() {
  echo "Usage: $0 <version> <output-iss-path>" >&2
  exit 2
}

if [ $# -lt 2 ]; then
  usage
fi

VERSION="$1"
ISS_PATH="$2"

# Guarded for the same reason as build-app-bundle.sh's: an empty version would
# substitute into empty AppVersion= and SirioSetup- lines, which the wizardless
# installer still accepts -- an installed Sirio with no version anywhere the
# updater can read one.
if [ -z "$VERSION" ]; then
  echo "error: version must not be empty" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Identifier, display name and the AppId come from the one identity source
# (#304); this script only renders their .iss wording. AppId must never be
# retyped or changed: Inno compares it to decide upgrade-in-place versus
# side-by-side, and the update path re-runs this installer expecting an
# in-place upgrade (spec §8.2).
. "$SCRIPT_DIR/identity.sh"

mkdir -p "$(dirname "$ISS_PATH")"

cat > "$ISS_PATH" <<EOF
; Generated by Scripts/build-inno.sh from Scripts/identity.sh (#304) and the
; release version -- do not edit by hand. The AppId GUID must never change:
; Inno compares it to decide upgrade-in-place versus side-by-side, and the
; updater re-runs this installer expecting an in-place upgrade (spec §8.2).
[Setup]
AppId={{${SIRIO_INNO_APP_ID}}
AppName=${SIRIO_DISPLAY_NAME}
AppVersion=${VERSION}
DefaultDirName={localappdata}\\Programs\\${SIRIO_DISPLAY_NAME}
DisableProgramGroupPage=yes
DefaultGroupName=${SIRIO_DISPLAY_NAME}
PrivilegesRequired=lowest
OutputBaseFilename=SirioSetup-${VERSION}
OutputDir=.
UninstallDisplayName=${SIRIO_DISPLAY_NAME}
UninstallDisplayIcon={app}\sirio.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

; The sibling rule (spec §1.4): sirioctl must sit next to sirio.exe. No
; WebView2Loader.dll ships: under MSVC (the release ABI) webview2-com-sys
; links WebView2LoaderStatic.lib, so the installed app starts without it.
[Files]
Source: "sirio.exe"; DestDir: "{app}"
Source: "sirioctl.exe"; DestDir: "{app}"

[Icons]
Name: "{group}\\${SIRIO_DISPLAY_NAME}"; Filename: "{app}\sirio.exe"

; Spec §7.5: chain the WebView2 Runtime bootstrapper only when the runtime is
; absent, silently, per-user (matching this never-elevating installer), and
; treat every failure -- missing registry key, failed download, bootstrapper
; itself -- as non-fatal. The Check function downloads to {tmp}, so a failed
; fetch never reaches the [Files] machinery that would abort the install; the
; [Run] entry runs under /VERYSILENT and nowait lets the setup finish while
; the bootstrapper does its work in the background.
[Run]
Filename: "{tmp}\MicrosoftEdgeWebView2Setup.exe"; Parameters: "/silent /install"; Flags: nowait skipifdoesntexist; Check: InstallWebView2RuntimeIfAbsent

[Code]
const
  WebView2ClientKey = 'Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';

function IsWebView2RuntimeInstalled: Boolean;
begin
  Result := RegValueExists(HKCU, WebView2ClientKey, 'pv')
        or RegValueExists(HKLM, WebView2ClientKey, 'pv');
end;

function InstallWebView2RuntimeIfAbsent: Boolean;
begin
  if IsWebView2RuntimeInstalled then
    Result := False
  else
    try
      DownloadTemporaryFile('https://go.microsoft.com/fwlink/?linkid=2124703',
        'MicrosoftEdgeWebView2Setup.exe', '', nil);
      Result := True;
    except
      Result := False;
    end;
end;
EOF

echo "$ISS_PATH"