//! The Oh-My-Pi adapter, ported from `TillerAgents/OhMyPiAdapter.swift`.

use std::path::Path;

use crate::error::PrepareError;
use crate::shell_quote::{json_string_literal, shell_quote};

/// The hook template, byte-faithful to the Swift original. `__TILLERCTL__`
/// and `__PANE__` are replaced by [`prepare`]; the JS braces are left
/// untouched (no `format!` interpolation).
const HOOK_TEMPLATE: &str = "// Generated by Tiller — drives the sidebar badge for this pane and
// reports the omp session identity for restore.
export default function (pi) {
    const notify = (status, extra = []) => {
        void pi.exec(__TILLERCTL__, [\"notify\", \"--session\", \"__PANE__\", \"--status\", status, ...extra]);
    };
    pi.on(\"session_start\", async (payload) => {
        const id = payload?.session?.id ?? payload?.sessionId ?? payload?.session?.file ?? \"\";
        notify(\"running\", id ? [\"--agent-session\", String(id)] : []);
    });
    pi.on(\"turn_start\", async () => { notify(\"running\"); });
    pi.on(\"turn_end\", async () => { notify(\"needs-input\"); });
    pi.on(\"session_shutdown\", async () => { notify(\"done\"); });
}
";

/// Oh-My-Pi (omp) supports native TypeScript hook files loaded via
/// `--hook <file>`. `prepare` writes the hook file inside the worktree —
/// never global config; the hook calls `tillerctl notify` on lifecycle
/// events to drive the badge.
pub struct OhMyPiAdapter;

impl super::AgentAdapter for OhMyPiAdapter {
    fn id(&self) -> &'static str {
        "omp"
    }

    fn display_name(&self) -> &'static str {
        "Oh-My-Pi"
    }

    fn executable_name(&self) -> &'static str {
        "oh-my-pi"
    }

    fn has_native_hooks(&self) -> bool {
        true
    }

    fn skill_markdown(&self) -> Option<&'static str> {
        // F-AGENT-SAFE-01: see `ClaudeCodeAdapter::skill_markdown`.
        Some(include_str!("../../../../skills/tiller/SKILL.md"))
    }

    fn prepare(
        &self,
        worktree_path: &str,
        pane_id: &str,
        tillerctl_path: &str,
    ) -> Result<(), PrepareError> {
        if let Some(markdown) = self.skill_markdown() {
            crate::install_skill(markdown, self.id(), worktree_path)?;
        }
        let dir = Path::new(worktree_path).join(".tiller");
        std::fs::create_dir_all(&dir)?;

        let hook = HOOK_TEMPLATE
            .replace("__TILLERCTL__", &json_string_literal(tillerctl_path))
            .replace("__PANE__", pane_id);

        std::fs::write(dir.join("omp-hook.ts"), hook)?;
        Ok(())
    }

    fn command(&self, worktree_path: &str, _pane_id: &str, _tillerctl_path: &str) -> String {
        let hook_path = format!("{worktree_path}/.tiller/omp-hook.ts");
        format!("oh-my-pi --hook {}", shell_quote(&hook_path))
    }

    fn resume_command(
        &self,
        worktree_path: &str,
        _pane_id: &str,
        _tillerctl_path: &str,
        session_ref: &str,
    ) -> Option<String> {
        let hook_path = format!("{worktree_path}/.tiller/omp-hook.ts");
        Some(format!(
            "oh-my-pi --hook {} --resume={}",
            shell_quote(&hook_path),
            shell_quote(session_ref)
        ))
    }

    fn acp_program(&self) -> Option<crate::AcpProgram> {
        // Oh-My-Pi is a pi fork running as a TUI; it has no ACP server.
        // `None` is the honest answer: a chat tab must not be offered
        // for it.
        None
    }

    fn summarizer_command(&self, prompt: &str) -> Option<String> {
        // The Swift original spells the program `omp`; the distribution
        // ships only `oh-my-pi` (no alias), so this follows the same
        // executable-name discipline as `command`/`resume_command` above.
        Some(format!("oh-my-pi --print --no-tools {}", shell_quote(prompt)))
    }
}
