//! The OpenCode adapter, ported from `TillerAgents/OpenCodeAdapter.swift`.

use std::path::Path;

use crate::error::PrepareError;
use crate::shell_quote::{json_string_literal, shell_quote};

/// The plugin template, byte-faithful to the Swift original. `__TILLERCTL__`
/// and `__PANE__` are replaced by [`prepare`]; the braces in the JS template
/// literal are left untouched (no `format!` interpolation).
const PLUGIN_TEMPLATE: &str =
    "// Generated by Tiller — reports the OpenCode session id for restore.
export const TillerSession = async ({ $ }) => {
  let reported = \"\"
  const tillerctl = __TILLERCTL__
  const pane = \"__PANE__\"
  return {
    event: async ({ event }) => {
      const id = event?.properties?.info?.id
      if (event?.type === \"session.updated\" && id && id !== reported) {
        reported = id
        await $`${tillerctl} session-ref --session ${pane} --ref ${id}`.quiet().nothrow()
      }
    },
  }
}
";

/// OpenCode has no lifecycle hook mechanism for status — Tiller watches the
/// pane's exit code. `prepare` writes a worktree-local plugin (never global
/// config) whose only job is reporting the session id via
/// `tillerctl session-ref`, keeping the status pipeline untouched.
pub struct OpenCodeAdapter;

impl super::AgentAdapter for OpenCodeAdapter {
    fn id(&self) -> &'static str {
        "opencode"
    }

    fn display_name(&self) -> &'static str {
        "OpenCode"
    }

    fn has_native_hooks(&self) -> bool {
        false
    }

    fn prepare(
        &self,
        worktree_path: &str,
        pane_id: &str,
        tillerctl_path: &str,
    ) -> Result<(), PrepareError> {
        let dir = Path::new(worktree_path).join(".opencode/plugin");
        std::fs::create_dir_all(&dir)?;

        let plugin = PLUGIN_TEMPLATE
            .replace("__TILLERCTL__", &json_string_literal(tillerctl_path))
            .replace("__PANE__", pane_id);

        std::fs::write(dir.join("tiller-session.js"), plugin)?;
        Ok(())
    }

    fn command(&self, _worktree_path: &str, _pane_id: &str, _tillerctl_path: &str) -> String {
        "opencode".to_string()
    }

    fn resume_command(
        &self,
        _worktree_path: &str,
        _pane_id: &str,
        _tillerctl_path: &str,
        session_ref: &str,
    ) -> Option<String> {
        Some(format!("opencode --session {}", shell_quote(session_ref)))
    }

    fn acp_program(&self) -> Option<crate::AcpProgram> {
        // OpenCode is a terminal-first CLI with no ACP server. `None` is
        // the honest answer: a chat tab must not be offered for it.
        None
    }

    fn summarizer_command(&self, prompt: &str) -> Option<String> {
        // `--pure` suppresses the TUI chrome so stdout is only the answer.
        Some(format!("opencode run --pure {}", shell_quote(prompt)))
    }
}
