query ChangeRequestHeader($owner: String!, $name: String!, $number: Int!) {
  repository(owner: $owner, name: $name) {
    mergeCommitAllowed squashMergeAllowed rebaseMergeAllowed autoMergeAllowed deleteBranchOnMerge
    pullRequest(number: $number) {
      ...ChangeSummary
      body baseRefOid headRefOid
      id locked viewerCanUpdate viewerCanClose viewerCanReopen viewerDidAuthor
      mergeStateStatus isCrossRepository viewerCanEnableAutoMerge autoMergeRequest { mergeMethod }
      labels(first: 20) { nodes { id name color } }
      additions
      deletions
      changedFiles
      allCommits: commits { totalCount }
      timelineItems(last: 100, itemTypes: [ISSUE_COMMENT, PULL_REQUEST_REVIEW, REVIEW_REQUESTED_EVENT, PULL_REQUEST_COMMIT, MERGED_EVENT, CLOSED_EVENT, REOPENED_EVENT, READY_FOR_REVIEW_EVENT, CONVERT_TO_DRAFT_EVENT]) {
        pageInfo { hasPreviousPage startCursor }
        nodes {
          __typename
          ... on IssueComment { id viewerCanUpdate author { login } body createdAt }
          ... on PullRequestReview { id viewerCanUpdate author { login } state body submittedAt comments(first: 50) { nodes { path line originalLine body } } }
          ... on ReviewRequestedEvent { actor { login } createdAt requestedReviewer { __typename ... on User { login } ... on Team { slug } } }
          ... on PullRequestCommit { commit { oid committedDate } }
          ... on MergedEvent { actor { login } createdAt }
          ... on ClosedEvent { actor { login } createdAt }
          ... on ReopenedEvent { actor { login } createdAt }
          ... on ReadyForReviewEvent { actor { login } createdAt }
          ... on ConvertToDraftEvent { actor { login } createdAt }
        }
      }
    }
  }
}
